### ISSUE TITLE
Published Package with AGP 8 support

### ISSUE THREAD

**Issue by okmanideep** [ravitejaavv/store_checker#24]
I guess this has already been merged. Just need to update version and publish the plugin

**Comment by potatosalad775** [comment]
Since the PR which resolves this issue is indeed merged, you can directly fetch package from this git repository as a temporary fix.

Simply edit your pubspec.yaml like below:

```
  store_checker:
    git:
      url: https://github.com/ravitejaavv/store_checker.git
      ref: master
```
